[package]
name = "lyr"
version = "0.1.0"
edition = "2021"

[dependencies]
aho-corasick = "0.7.18"
clap = { version = "3.2.16", features = ["derive"] }
env_logger = "0.9.0"
fancy-regex = "0.10.0"
lofty = "0.7.3"
log = "0.4.17"
once_cell = "1.13.0"
reqwest = "0.11.11"
serde = { version = "1.0.140", features = ["derive"] }
thiserror = "1.0.31"
toml = "0.5.9"
tokio = { version = "1.20.1", features = ["rt", "macros", "rt-multi-thread"] }
dirs = "4.0.0"