name: CI

on:
  push:
    paths-ignore:
      - 'LICENSE-*'
      - '**/*.md'
      - '.gitignore'
      - 'CHANGELOG.md'
    branches:
      - master
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
#  test:
#    name: Tests
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions-rs/toolchain@v1
#        with:
#          profile: minimal
#          toolchain: stable
#          override: true
#      - run: cargo test --all-features --tests
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - run: rustup component add clippy
      - run: cargo clippy --all-features -- -Dclippy::all -Dclippy::pedantic
  style:
    name: Style
    runs-on: ubuntu-latest
    steps:
      -   uses: actions/checkout@v2
      -   uses: actions-rs/toolchain@v1
          with:
            profile: minimal
            toolchain: nightly
            override: true
      -   run: rustup component add rustfmt
      -   run: cargo fmt -- --check